name: Composer and NPM Package Diff
on:
  pull_request:
    paths:
      - 'composer.lock'
      - 'package-lock.json'
permissions:
  contents: write
  pull-requests: write
jobs:
  composer-diff:
    name: Composer Diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate composer diff
        id: composer_diff
        uses: IonBazan/composer-diff-action@v1
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff_exit_code != 0 }}
        with:
          header: composer-diff
          message: |
            <strong>Composer Changes</strong>

            ${{ steps.composer_diff.outputs.composer_diff }}
  npm-diff:
    name: NPM Lockfile Diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: NPM Lockfile Changes
        uses: codepunkt/npm-lockfile-changes@main
        with:
          token: ${{ github.token }}
          updateComment: true
